"""The hidden programs of the lisp-interpreter task: (name, program, stdout, exit code, text stderr must hold)."""

CASES = [
    ("arithmetic", "(display (+ 1 2 3)) (newline) (display (- 10 4 3)) (newline) (display (* 2 3 4)) (newline) (display (- 5)) (newline)", "6\n3\n24\n-5\n", 0, ""),
    ("division", "(display (/ 10 2)) (newline) (display (/ 1 2)) (newline) (display (quotient 17 5)) (display \" \") (display (remainder 17 5)) (display \" \") (display (modulo -7 3)) (newline)", "5\n0.5\n3 2 2\n", 0, ""),
    ("bignum", "(define (fact n) (if (= n 0) 1 (* n (fact (- n 1))))) (display (fact 30)) (newline)", "265252859812191058636308480000000\n", 0, ""),
    ("comparisons", "(display (< 1 2 3)) (display (< 1 3 2)) (display (= 2 2 2)) (display (>= 3 3 1)) (newline)", "#t#f#t#t\n", 0, ""),
    ("booleans", "(display (not #f)) (display (not 0)) (display (and 1 2)) (display (and 1 #f 2)) (display (or #f 7)) (display (or)) (display (and)) (newline)", "#t#f2#f7#f#t\n", 0, ""),
    ("define-and-call", "(define x 10) (define (square n) (* n n)) (display (square x)) (newline)", "100\n", 0, ""),
    ("closures", "(define (make-counter) (let ((n 0)) (lambda () (set! n (+ n 1)) n))) (define c (make-counter)) (c) (c) (display (c)) (define d (make-counter)) (display (d)) (newline)", "31\n", 0, ""),
    ("higher-order", "(define (compose f g) (lambda (x) (f (g x)))) (define inc (lambda (x) (+ x 1))) (display ((compose inc inc) 5)) (display \" \") (display (map (lambda (x) (* x x)) '(1 2 3))) (display \" \") (display (filter (lambda (x) (> x 2)) '(1 2 3 4))) (newline)", "7 (1 4 9) (3 4)\n", 0, ""),
    ("lists", "(display (cons 1 '(2 3))) (display (car '(a b c))) (display (cdr '(a b c))) (display (list 1 (list 2 3) '())) (display (length '(1 2 3 4))) (display (append '(1 2) '(3) '(4 5))) (display (reverse '(1 2 3))) (newline)", "(1 2 3)a(b c)(1 (2 3) ())4(1 2 3 4 5)(3 2 1)\n", 0, ""),
    ("pairs", "(display (cons 1 2)) (display (pair? '())) (display (null? '())) (display (list? '(1 2))) (display (list? (cons 1 2))) (newline)", "(1 . 2)#f#t#t#f\n", 0, ""),
    ("quote", "(display '(define x (quote y))) (display (quote sym)) (display (symbol? 'a)) (display (eq? 'a 'a)) (display (equal? '(1 (2)) '(1 (2)))) (display (eq? '(1) '(1))) (newline)", "(define x (quote y))sym#t#t#t#f\n", 0, ""),
    ("strings", "(display \"hello\\nworld\") (newline) (display (string-append \"a\" \"b\" \"c\")) (display (string-length \"abcd\")) (display (number->string 42)) (display (string? \"x\")) (newline) (display '(\"in\" \"list\")) (newline)", "hello\nworld\nabc442#t\n(\"in\" \"list\")\n", 0, ""),
    ("let-forms", "(define x 1) (let ((x 2) (y x)) (display y)) (let* ((a 2) (b (* a 3))) (display b)) (letrec ((even? (lambda (n) (if (= n 0) #t (odd? (- n 1))))) (odd? (lambda (n) (if (= n 0) #f (even? (- n 1)))))) (display (even? 100))) (newline)", "16#t\n", 0, ""),
    ("cond", "(define (sign n) (cond ((< n 0) 'negative) ((= n 0) 'zero) (else 'positive))) (display (map sign '(-3 0 9))) (newline)", "(negative zero positive)\n", 0, ""),
    ("begin-set", "(define x 1) (begin (set! x (+ x 1)) (set! x (* x 10))) (display x) (newline)", "20\n", 0, ""),
    ("variadic", "(define (count . args) (length args)) (display (count 1 2 3)) (display ((lambda args args) 1 2)) (display (apply + 1 2 '(3 4))) (newline)", "3(1 2)10\n", 0, ""),
    ("tail-calls", "(define (loop n acc) (if (= n 0) acc (loop (- n 1) (+ acc 1)))) (display (loop 1000000 0)) (newline)", "1000000\n", 0, ""),
    ("tail-cond", "(define (count-down n) (cond ((= n 0) 'done) (else (count-down (- n 1))))) (display (count-down 300000)) (newline)", "done\n", 0, ""),
    ("deep-recursion", "(define (depth n) (if (= n 0) 0 (+ 1 (depth (- n 1))))) (display (depth 5000)) (newline)", "5000\n", 0, ""),
    ("mutual-recursion", "(define (ev? n) (if (= n 0) #t (od? (- n 1)))) (define (od? n) (if (= n 0) #f (ev? (- n 1)))) (display (ev? 100001)) (newline)", "#f\n", 0, ""),
    ("accumulate", "(define (range a b) (if (>= a b) '() (cons a (range (+ a 1) b)))) (define (sum l) (if (null? l) 0 (+ (car l) (sum (cdr l))))) (display (sum (range 0 100))) (newline)", "4950\n", 0, ""),
    ("sort", "(define (insert x l) (cond ((null? l) (list x)) ((< x (car l)) (cons x l)) (else (cons (car l) (insert x (cdr l)))))) (define (sort l) (if (null? l) '() (insert (car l) (sort (cdr l))))) (display (sort '(5 3 9 1 4))) (newline)", "(1 3 4 5 9)\n", 0, ""),
    ("comments", "; a comment\n(display 1) ; another\n(newline)", "1\n", 0, ""),
    ("procedures-print", "(display (procedure? car)) (display (procedure? (lambda (x) x))) (display (number? 'a)) (newline)", "#t#t#f\n", 0, ""),
    ("min-max-abs", "(display (min 3 1 2)) (display (max 3 1 2)) (display (abs -7)) (newline)", "137\n", 0, ""),
    ("undefined-variable", "(display 1) (newline) (display nope)", "1\n", 1, "undefined variable"),
    ("not-a-procedure", "(display 2) (5 3)", "2", 1, "error"),
    ("car-of-empty", "(car '())", "", 1, "error"),
    ("division-by-zero", "(display (/ 1 0))", "", 1, "error"),
    ("error-call", "(display \"before\") (error \"boom\" 42) (display \"after\")", "before", 1, "boom"),
]
