// Derived from Open Multi-Agent (MIT), Copyright (c) Shenzhen YuanASI Technology
// Co., Ltd. and open-multi-agent contributors. Modified for invisible_dots.
// See guest-runtime/engine/LICENSE and UPSTREAM.md.
/**
 * @fileoverview Core type definitions for the open-multi-agent orchestration framework.
 *
 * All public types are exported from this single module. Downstream modules
 * import only what they need, keeping the dependency graph acyclic.
 */

import type { ZodSchema } from 'zod'

// ---------------------------------------------------------------------------
// Content blocks
// ---------------------------------------------------------------------------

/** Plain-text content produced by a model or supplied by the user. */
export interface TextBlock {
  readonly type: 'text'
  readonly text: string
}

/** Provider-native reasoning / thinking content emitted alongside normal text. */
export interface ReasoningBlock {
  readonly type: 'reasoning'
  readonly text: string
  /**
   * Provider-issued signature proving the reasoning was generated by the
   * model. Used by:
   *   - Anthropic / Bedrock: required to echo back unchanged on the next
   *     turn to continue a multi-turn tool-use conversation with extended
   *     thinking; the API rejects edited or missing signatures.
   *   - Gemini 3: optional `thoughtSignature` attached to thought-summary
   *     Parts; recommended to round-trip per Gemini docs ("always pass all
   *     signatures back as received") but not strictly required.
   * Absent for providers that don't sign reasoning (Gemini 2.5 thought
   * summaries, OpenAI o-series) and for reasoning that originated outside
   * the provider being addressed.
   */
  readonly signature?: string
  /**
   * Opaque encrypted thinking content returned by Anthropic when its safety
   * system blocks the raw reasoning text. The block must still be echoed
   * back on subsequent turns to satisfy the protocol, but its contents are
   * not human-readable. Carried separately from `text` because the wire
   * format for redacted blocks is distinct (`redacted_thinking` vs
   * `thinking`).
   */
  readonly redactedData?: string
  /**
   * Name of the {@link LLMAdapter} that produced this block, stamped at
   * extraction time on the native-to-IR path (both `chat` responses and
   * streaming final payloads). Consumed by outbound IR-to-native conversion
   * to decide between native echo and the `<thinking>` text fallback for
   * adapters whose {@link LLMAdapter.capabilities.echoesReasoning} is
   * `'own-issued'`.
   *
   * Typed as `string` rather than `SupportedProvider` so third-party adapter
   * implementations can stamp their own adapter name without modifying the
   * core enum.
   *
   * Optional for backwards compatibility with externally constructed IR.
   * Outbound paths treat `undefined` as "unknown provenance → cannot
   * native-echo".
   */
  readonly provenance?: string
}

/**
 * A request by the model to invoke a named tool with a structured input.
 * The `id` is unique per turn and is referenced by {@link ToolResultBlock}.
 */
export interface ToolUseBlock {
  readonly type: 'tool_use'
  readonly id: string
  readonly name: string
  readonly input: Record<string, unknown>
  /**
   * Provider-issued signature attached to a tool call to prove the call was
   * generated under extended thinking. Currently only used by Gemini
   * (`thoughtSignature`), which is a top-level field on the Part containing
   * the functionCall — an asymmetry from Anthropic, which signs the
   * preceding {@link ReasoningBlock} instead. Echo back unchanged on
   * subsequent turns to satisfy Gemini 3+'s strict validation.
   */
  readonly signature?: string
}

/**
 * The result of executing a tool, keyed back to the originating
 * {@link ToolUseBlock} via `tool_use_id`.
 */
export interface ToolResultBlock {
  readonly type: 'tool_result'
  readonly tool_use_id: string
  readonly content: ToolResultContent
  readonly is_error?: boolean
}

/** Inline bytes or a remote reference supplied as model-visible tool output. */
export type ToolResultMediaSource =
  | {
      readonly type: 'base64'
      /** IANA media type for the encoded bytes. */
      readonly media_type: string
      /** Raw base64 data without a data-URL prefix. */
      readonly data: string
    }
  | {
      readonly type: 'url'
      /** IANA media type expected at the reference. */
      readonly media_type: string
      /** Absolute HTTP(S) URL. Provider/model support still varies. */
      readonly url: string
    }

/** Text part in a rich, model-visible tool result. */
export interface ToolResultTextPart {
  readonly type: 'text'
  readonly text: string
}

/** Image part in a rich, model-visible tool result. */
export interface ToolResultImagePart {
  readonly type: 'image'
  readonly source: ToolResultMediaSource
}

/** File part in a rich, model-visible tool result. */
export interface ToolResultFilePart {
  readonly type: 'file'
  /** Display name forwarded when the provider wire format supports one. */
  readonly filename: string
  readonly source: ToolResultMediaSource
}

/** A part accepted inside a rich tool result. */
export type ToolResultContentPart =
  | ToolResultTextPart
  | ToolResultImagePart
  | ToolResultFilePart

/** Content returned to the model for one tool call. */
export type ToolResultContent = string | readonly ToolResultContentPart[]

/** A base64-encoded image passed to or returned from a model. */
export interface ImageBlock {
  readonly type: 'image'
  readonly source: {
    readonly type: 'base64'
    readonly media_type: string
    readonly data: string
  }
}

/**
 * A video passed to a model as inline bytes or a remote reference.
 *
 * Unlike {@link ImageBlock}, a `url` source is dereferenced by the provider
 * rather than by OMA, so the reference leaves the process. Public entry points
 * validate it the same way tool-result media is validated: absolute HTTP(S)
 * only, and raw canonical base64 with a parameterless MIME type for inline
 * bytes. Provider-private reference schemes are not accepted.
 */
export interface VideoBlock {
  readonly type: 'video'
  readonly source:
    | {
        readonly type: 'base64'
        /** IANA media type for the encoded bytes. */
        readonly media_type: string
        /** Raw base64 data without a data-URL prefix. */
        readonly data: string
      }
    | {
        readonly type: 'url'
        /** IANA media type expected at the reference. */
        readonly media_type: string
        /** Absolute HTTP(S) URL. Provider/model support still varies. */
        readonly url: string
      }
}

/** Union of all content block variants that may appear in a message. */
export type ContentBlock = ReasoningBlock | TextBlock | ToolUseBlock | ToolResultBlock | ImageBlock | VideoBlock

/**
 * A single message in a conversation thread.
 * System messages are passed separately via {@link LLMChatOptions.systemPrompt}.
 */
export interface LLMMessage {
  readonly role: 'user' | 'assistant'
  readonly content: ContentBlock[]
}

/** Context management strategy for long-running agent conversations. */
export type ContextStrategy =
  | { type: 'sliding-window'; maxTurns: number }
  | { type: 'summarize'; maxTokens: number; summaryModel?: string }
  | {
      type: 'compact'
      /** Estimated token threshold that triggers compaction. Compaction is skipped when below this. */
      maxTokens: number
      /** Number of recent turn pairs (assistant+user) to keep intact. Default: 4. */
      preserveRecentTurns?: number
      /** Minimum chars in a tool_result content to qualify for compaction. Default: 200. */
      minToolResultChars?: number
      /** Minimum chars in an assistant text block to qualify for truncation. Default: 2000. */
      minTextBlockChars?: number
      /** Maximum chars to keep from a truncated text block (head excerpt). Default: 200. */
      textBlockExcerptChars?: number
    }
  | {
    type: 'custom'
    /**
     * Compaction callback. Invoked before every LLM turn including the first,
     * so implementations that should only fire past a token threshold must
     * self-gate inside this function.
     */
    compress: (
      messages: LLMMessage[],
      estimatedTokens: number,
    ) => Promise<LLMMessage[]> | LLMMessage[]
  }

/** Token accounting for a single API call. */
export interface TokenUsage {
  readonly input_tokens: number
  readonly output_tokens: number
}

/** Scalar trace attribute values supported by the v2 record schema. */
export type TraceAttributeValue =
  | string
  | number
  | boolean
  | readonly string[]
  | readonly number[]
  | readonly boolean[]

/** Stable identity for one logical run and its current execution attempt. */
export interface RunIdentity {
  /** Logical run identifier. Preserved across checkpoint restore. */
  readonly runId: string
  /** One-based execution attempt. Incremented by each restore. */
  readonly attempt: number
  /** W3C-compatible 32-character lowercase hexadecimal trace identifier. */
  readonly traceId: string
  /** W3C-compatible 16-character lowercase hexadecimal root span identifier. */
  readonly rootSpanId: string
  /** Continuation links, currently used by checkpoint restore. */
  readonly links?: readonly TraceLink[]
}

/** A relationship from this execution attempt to an earlier trace. */
export interface TraceLink {
  readonly traceId: string
  readonly spanId: string
  readonly relation: 'continued_from' | 'depends_on' | 'consumed' | 'delegated_from'
  readonly attributes?: Readonly<Record<string, TraceAttributeValue>>
}

export type RunStatusCode =
  | 'ok'
  | 'error'
  | 'cancelled'
  | 'timeout'
  | 'budget_exhausted'
  | 'rejected'
  | 'suspended'
  | 'skipped'

/** Normalised top-level outcome. */
export interface RunStatus {
  readonly code: RunStatusCode
  readonly message?: string
}

export type TraceErrorKind =
  | 'provider'
  | 'tool'
  | 'framework'
  | 'callback'
  | 'validation'
  | 'timeout'
  | 'cancellation'
  | 'budget'
  | 'store'
  | 'exporter'
  | 'unknown'

/** JSON-safe, redacted error details for results and future trace records. */
export interface StructuredTraceError {
  readonly kind: TraceErrorKind
  readonly code?: string
  readonly name?: string
  readonly message?: string
  readonly retryable?: boolean
  readonly httpStatus?: number
  readonly provider?: string
  readonly attempt?: number
}

/** Durable approval boundary represented by an {@link ApprovalRequest}. */
export type ApprovalScope = 'plan' | 'task_round' | 'task_dispatch' | 'tool_call'

/** Exact checkpoint-resumable plan payload shown to a reviewer. */
export interface PlanApprovalContent {
  readonly kind: 'plan'
  /** Whether approval continues execution or returns the already-built plan. */
  readonly continuation: 'execute' | 'plan_only'
  readonly tasks: readonly TaskSnapshot[]
}

/** Exact checkpoint-resumable legacy-round payload shown to a reviewer. */
export interface TaskRoundApprovalContent {
  readonly kind: 'task_round'
  readonly completedTasks: readonly TaskSnapshot[]
  readonly nextTasks: readonly TaskSnapshot[]
}

/** Exact checkpoint-resumable task-dispatch payload shown to a reviewer. */
export interface TaskDispatchApprovalContent {
  readonly kind: 'task_dispatch'
  readonly task: TaskSnapshot
}

/** Exact validated tool invocation shown to a reviewer. */
export interface ToolCallApprovalContent {
  readonly kind: 'tool_call'
  readonly toolName: string
  /** Model-issued input retained so restore can detect a changed request. */
  readonly rawInput: Readonly<Record<string, unknown>>
  /** Zod-validated input that the tool implementation will receive. */
  readonly input: Readonly<Record<string, unknown>>
  readonly agentName: string
  readonly taskId: string
  readonly toolCallId: string
  readonly consequential: boolean
}

/** Review payload supported by the durable approval subsystem. */
export type ApprovalRequestContent =
  | PlanApprovalContent
  | TaskRoundApprovalContent
  | TaskDispatchApprovalContent
  | ToolCallApprovalContent

/** Immutable, content-bound request persisted before a run reports suspension. */
export interface ApprovalRequest {
  readonly version: 1
  readonly id: string
  readonly runId: string
  readonly scope: ApprovalScope
  /** Stable boundary discriminator (for example a task or tool-call id). */
  readonly boundary: string
  /** SHA-256 of the canonical scope/boundary/content payload. */
  readonly requestHash: string
  readonly requestedAt: string
  readonly reason?: string
  readonly content: ApprovalRequestContent
}

/** Required human or service identity attached to a durable decision. */
export interface ApprovalReviewer {
  readonly id: string
  readonly displayName?: string
}

/** Primary durable fact recording who decided what and when. */
export interface ApprovalDecisionRecord {
  readonly version: 1
  readonly requestId: string
  readonly runId: string
  readonly scope: ApprovalScope
  readonly requestHash: string
  readonly decision: 'approved' | 'rejected'
  readonly reviewer: ApprovalReviewer
  readonly decidedAt: string
}

/** Stored approval ledger row. The request remains immutable after creation. */
export interface ApprovalRecord {
  readonly version: 1
  readonly request: ApprovalRequest
  readonly decision?: ApprovalDecisionRecord
}

/** Input accepted by {@link decideApproval}. */
export interface ApprovalDecisionInput {
  readonly requestId: string
  /** Reviewer-side optimistic binding to the exact request that was inspected. */
  readonly requestHash: string
  readonly decision: 'approve' | 'reject'
  readonly reviewer: ApprovalReviewer
}

/** Additive result fields introduced by Observability v2. */
export interface RunOutcomeFields {
  /**
   * Runtime results always include this field. It is optional in the first
   * compatible 1.x type release so existing hand-written result fixtures keep
   * compiling; it can become required in a later compatibility window.
   */
  readonly identity?: RunIdentity
  /** Runtime results always include this field; see {@link identity}. */
  readonly status?: RunStatus
  readonly errorInfo?: StructuredTraceError
  /** Echo of validated metadata; present at runtime whenever the caller provided it. */
  readonly metadata?: Readonly<Record<string, TraceAttributeValue>>
  /** Additive, machine-readable execution warnings attached by the runtime. */
  readonly flags?: readonly RunFlag[]
  /**
   * True when an opt-in consequential-tool guard stopped a tool call because
   * no application approval gate was available. Re-run with an `onToolCall`
   * gate that returns `allow` to approve the call, or `deny` to reject it.
   */
  readonly confirmationRequired?: boolean
  /** Requests that must receive durable decisions before {@link OpenMultiAgent.restore}. */
  readonly pendingApprovals?: readonly ApprovalRequest[]
  /** Durable decisions consumed by this logical run. */
  readonly approvalDecisions?: readonly ApprovalDecisionRecord[]
}

/** Machine-readable warnings that describe how a run was governed. */
export type RunFlag =
  | 'consequential-no-independence'
  | 'governance-overridden'
  | 'review-skipped-due-to-budget'

/** Normalised response returned by every {@link LLMAdapter} implementation. */
export interface LLMResponse {
  readonly id: string
  readonly content: ContentBlock[]
  readonly model: string
  readonly stop_reason: string
  readonly usage: TokenUsage
}

/** The serialisable tool schema sent to the LLM provider. */
export interface LLMToolDef {
  readonly name: string
  readonly description: string
  /** JSON Schema object describing the tool's `input` parameter. */
  readonly inputSchema: Record<string, unknown>
}

/**
 * Context injected into every tool execution.
 *
 * Both `abortSignal` and `abortController` are provided so that tools and the
 * executor can choose the most ergonomic API for their use-case:
 *
 * - Long-running shell commands that need to kill a child process can use
 *   `abortController.signal` directly.
 * - Simple cancellation checks can read `abortSignal?.aborted`.
 *
 * When constructing a context, set `abortController` and derive `abortSignal`
 * from it, or provide both independently.
 */
export interface ToolUseContext {
  /** High-level description of the agent invoking this tool. */
  readonly agent: AgentInfo
  /**
   * Convenience reference to the abort signal.
   * Equivalent to `abortController?.signal` when an `abortController` is set.
   */
  readonly abortSignal?: AbortSignal
  /**
   * Full abort controller, available when the caller needs to inspect or
   * programmatically abort the signal.
   * Tools should prefer `abortSignal` for simple cancellation checks.
   */
  readonly abortController?: AbortController
  /** Arbitrary caller-supplied metadata (session ID, request ID, etc.). */
  readonly metadata?: Readonly<Record<string, unknown>>
  /** Run ID associated with this tool call, when available. */
  readonly runId?: string
  /** Task ID associated with this tool call, when available. */
  readonly taskId?: string
  /**
   * Stable model-issued ID for this tool call. Mid-task checkpoint restore
   * reuses the same ID when an uncommitted call must be executed again, so a
   * consequential tool can use it as an external idempotency key.
   */
  readonly toolCallId?: string
}

/** Minimal descriptor for the agent that is invoking a tool. */
export interface AgentInfo {
  readonly name: string
  readonly role: string
  readonly model: string
}

/** Context passed to the optional per-call tool gate. */
export interface ToolCallContext {
  readonly toolName: string
  readonly input: Record<string, unknown>
  readonly agentName: string
  /** True when the registered tool definition declares real side effects. */
  readonly consequential?: boolean
  readonly runId?: string
  readonly taskId?: string
  /** Stable model-issued ID for this tool call, when available. */
  readonly toolCallId?: string
}

/** Decision returned by the optional per-call tool gate. */
export type ToolCallDecision =
  | { readonly action: 'allow' }
  | { readonly action: 'deny'; readonly reason?: string }
  | { readonly action: 'suspend'; readonly reason?: string }

/** Optional middleware invoked after input validation and before tool execution. */
export type ToolCallGate = (context: ToolCallContext) => ToolCallDecision | Promise<ToolCallDecision>

/** Metadata attached to tool results when a per-call gate runs. */
export interface ToolCallGateMetadata {
  readonly action: ToolCallDecision['action']
  readonly reason?: string
}

/**
 * Optional side-channel metadata a tool may attach to its result.
 * Not shown to the LLM — the runner reads it for accounting purposes.
 */
export interface ToolResultMetadata {
  /** Per-call gate decision, if an onToolCall hook evaluated this tool call. */
  readonly toolCallGate?: ToolCallGateMetadata
  /** Internal hand-off from ToolExecutor to AgentRunner for a suspend decision. */
  readonly approvalRequestContent?: ToolCallApprovalContent
  /** Durable decision used instead of re-running an already-reviewed gate. */
  readonly approvalDecision?: ApprovalDecisionRecord
  /** Integrity error that prevented an approved tool invocation from executing. */
  readonly approvalError?: string
}

/** Value returned by a tool's `execute` function. */
export interface ToolResult<TData = string> {
  /**
   * Application-owned result. Existing tools may keep returning a string.
   * Non-string values require an explicit {@link modelOutput} so the framework
   * never guesses how to serialize application data for a model.
   */
  readonly data: TData
  /**
   * Optional model-visible representation, validated and defensively copied at
   * the tool boundary. When omitted, string `data` is forwarded unchanged.
   */
  readonly modelOutput?: ToolResultContent
  readonly isError?: boolean
  readonly metadata?: ToolResultMetadata
}

/**
 * A tool registered with the framework.
 *
 * `inputSchema` is a Zod schema used for validation before `execute` is called.
 * At API call time it is converted to JSON Schema for {@link LLMToolDef}, unless
 * `llmInputSchema` is set (e.g. MCP tools ship JSON Schema from the server).
 *
 * `outputSchema` is optional runtime validation for `ToolResult.data`.  When
 * set and validation fails, execution returns an error ToolResult instead of
 * propagating invalid output.
 */
export interface ToolDefinition<TInput = Record<string, unknown>, TData = string> {
  readonly name: string
  readonly description: string
  readonly inputSchema: ZodSchema<TInput>
  /**
   * Marks a tool whose grant permits real side effects. Omitted/false means
   * benign for undeclared-run fallback classification. The runtime never
   * infers this value from prompts, tool arguments, or keywords.
   */
  readonly consequential?: boolean
  /**
   * Optional runtime validator for the application-owned `ToolResult.data`.
   *
   * **Not to be confused with {@link AgentConfig.outputSchema}**, which
   * validates an agent's final JSON answer. This one only guards a single
   * tool's application result.
   */
  readonly outputSchema?: ZodSchema<TData>
  /**
   * When present, used as {@link LLMToolDef.inputSchema} as-is instead of
   * deriving JSON Schema from `inputSchema` (Zod).
   */
  readonly llmInputSchema?: Record<string, unknown>
  /**
   * Per-tool maximum output length in characters. When set, tool output
   * exceeding this limit is truncated (head + tail with a marker in between).
   * Takes priority over {@link AgentConfig.maxToolOutputChars}.
   */
  readonly maxOutputChars?: number
  execute(input: TInput, context: ToolUseContext): Promise<ToolResult<TData>>
}

/** Configuration for agent loop detection. */
export interface LoopDetectionConfig {
  /**
   * Maximum consecutive times the same tool call (name + args) or text
   * output can repeat before detection triggers. Default: `3`.
   */
  readonly maxRepetitions?: number
  /**
   * Number of recent turns to track for repetition analysis. Default: `4`.
   */
  readonly loopDetectionWindow?: number
  /**
   * Action to take when a loop is detected.
   * - `'warn'`      — inject a "you appear stuck" message, give the LLM one
   *                    more chance; terminate if the loop persists (default)
   * - `'terminate'` — stop the run immediately
   * - `function`    — custom callback (sync or async); return `'continue'`,
   *                    `'inject'`, or `'terminate'` to control the outcome
   */
  readonly onLoopDetected?: 'warn' | 'terminate' | ((info: LoopDetectionInfo) => 'continue' | 'inject' | 'terminate' | Promise<'continue' | 'inject' | 'terminate'>)
}

/** Diagnostic payload emitted when a loop is detected. */
export interface LoopDetectionInfo {
  readonly kind: 'tool_repetition' | 'text_repetition'
  /** Number of consecutive identical occurrences observed. */
  readonly repetitions: number
  /** Human-readable description of the detected loop. */
  readonly detail: string
}

/** A single recorded tool invocation within a run. */
export interface ToolCallRecord {
  readonly toolName: string
  readonly input: Record<string, unknown>
  readonly output: string
  /** Wall-clock duration in milliseconds. */
  readonly duration: number
}

/** The final result produced when an agent run completes (or fails). */
export interface AgentRunResult extends RunOutcomeFields {
  readonly success: boolean
  readonly output: string
  readonly messages: LLMMessage[]
  readonly tokenUsage: TokenUsage
  readonly toolCalls: ToolCallRecord[]
  /** True when the run was terminated or warned due to loop detection. */
  readonly loopDetected?: boolean
  /** True when the run stopped because token budget was exceeded. */
  readonly budgetExceeded?: boolean
  /**
   * The underlying thrown error when `success` is false due to an exception
   * (e.g. a provider `APIError` carrying `.status`), preserved so retry logic
   * can classify it as retryable vs terminal. `undefined` for app-level
   * failures. In-process only — collapses to `{}` if the result is
   * JSON-serialized.
   */
  readonly error?: unknown
}

/**
 * Explicit hard requirements for task-to-agent selection.
 *
 * Hard constraints use only resolved tool grants, backend discriminants
 * and caller-declared capability tags. They are never inferred
 * from `systemPrompt`, task prose, names, or other unstructured text.
 */
export interface TaskRequirements {
  readonly requiredTools?: readonly string[]
  readonly requiredCapabilities?: readonly string[]
  readonly requiredBackend?: 'llm' | 'process' | 'acp'
}

/** Bounded, trace-safe business references attached to one task. */
export type TaskMetadata = Readonly<Record<string, TraceAttributeValue>>

/** Reassign a task that has not started. */
export interface PlanPatchRetarget {
  readonly taskId: string
  readonly assignee: string
}

/** Accepted description of one runtime plan repair. */
export interface PlanRevision {
  readonly id: string
  readonly version: number
  readonly triggerTaskId: string
  readonly trigger: 'success' | 'failure' | 'verification_rejected'
  readonly reason: string
  readonly addedTasks: Readonly<Record<string, string>>
  readonly retargetedTasks: readonly PlanPatchRetarget[]
  readonly supersededTaskIds: readonly string[]
  readonly createdAt: string
}

/** Valid states for a {@link Task}. */
export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'blocked' | 'skipped'

/** Configuration for opt-in checkpoint persistence. */
export interface CheckpointOptions {
  /**
   * Set to `false` to disable a default checkpoint config for a single run.
   * Omitted or `true` enables checkpointing.
   */
  readonly enabled?: boolean
  /** Durable store used for checkpoint records. Defaults to the team's shared-memory store. */
  readonly store?: MemoryStore
  /** Exact store key for the latest checkpoint. Takes precedence over `runId`. */
  readonly key?: string
  /** Logical run id used to derive a checkpoint key when `key` is omitted. */
  readonly runId?: string
}

/** Serializable form of a {@link MemoryEntry}. */
export interface MemoryEntrySnapshot {
  readonly key: string
  readonly value: string
  readonly metadata?: Readonly<Record<string, unknown>>
  readonly createdAt: string
  readonly expiresAtTurn?: number
}

/** Serializable form of {@link SharedMemory}. */
export interface SharedMemorySnapshot {
  readonly version: 1
  readonly turnCount: number
  readonly entries: readonly MemoryEntrySnapshot[]
}

/** Serializable form of an inter-agent message. */
export interface MessageSnapshot {
  readonly id: string
  readonly from: string
  readonly to: string
  readonly content: string
  readonly timestamp: string
}

/** Serializable read-state for one agent on the MessageBus. */
export interface MessageReadStateSnapshot {
  readonly agentName: string
  readonly messageIds: readonly string[]
}

/** Serializable form of MessageBus state. Runtime subscribers are not persisted. */
export interface MessageBusSnapshot {
  readonly version: 1
  readonly messages: readonly MessageSnapshot[]
  readonly readState: readonly MessageReadStateSnapshot[]
}

/** Serializable form of a {@link Task}. */
export interface TaskSnapshot {
  readonly id: string
  readonly title: string
  readonly description: string
  readonly status: TaskStatus
  readonly assignee?: string
  readonly dependsOn?: readonly string[]
  readonly memoryScope?: 'dependencies' | 'all'
  readonly dependencyPayload?: 'output' | 'structured' | 'both'
  readonly role?: string
  readonly priority?: 'low' | 'normal' | 'high' | 'critical'
  readonly metadata?: TaskMetadata
  readonly requires?: TaskRequirements
  readonly result?: string
  readonly createdAt: string
  readonly updatedAt: string
  readonly maxRetries?: number
  readonly retryDelayMs?: number
  readonly retryBackoff?: number
  readonly supersededByRevision?: number
  readonly recoveredByRevision?: number
}

/** Legacy serializable state of a {@link TaskQueue}. */
export interface TaskQueueSnapshotV1 {
  readonly version: 1
  readonly tasks: readonly TaskSnapshot[]
  readonly pending: readonly string[]
  readonly inProgress: readonly string[]
  readonly completed: readonly string[]
  readonly failed: readonly string[]
  readonly blocked: readonly string[]
  readonly skipped: readonly string[]
}

/** Serializable adaptive-plan state of a {@link TaskQueue}. */
export interface TaskQueueSnapshotV2 {
  readonly version: 2
  readonly tasks: readonly TaskSnapshot[]
  readonly pending: readonly string[]
  readonly inProgress: readonly string[]
  readonly completed: readonly string[]
  readonly failed: readonly string[]
  readonly blocked: readonly string[]
  readonly skipped: readonly string[]
  readonly planRevision: number
  readonly planRevisions: readonly PlanRevision[]
}

/** Serializable state of a {@link TaskQueue}. */
export type TaskQueueSnapshot = TaskQueueSnapshotV1 | TaskQueueSnapshotV2

/** Result recorded for a completed task inside a checkpoint. */
export interface CompletedTaskCheckpoint {
  readonly taskId: string
  readonly assignee?: string
  readonly result?: string
  /**
   * Full JSON-serializable task result. The in-process-only `error` object is
   * deliberately omitted; normalized `status` / `errorInfo` remain available.
   */
  readonly agentResult?: Omit<AgentRunResult, 'error'>
}

/** A tool result durably recorded before an in-flight task completes. */
export interface ToolCallCommitCheckpoint {
  /** Result block replayed to the model without re-executing the tool. */
  readonly result: ToolResultBlock
  /** Public tool-call record carried into the eventual agent result. */
  readonly record: ToolCallRecord
  /** Nested-agent usage returned by tools such as `delegate_to_agent`. */
  readonly delegationUsage?: TokenUsage
}

/** One model-requested tool call in an in-flight assistant turn. */
export interface PendingToolCallCheckpoint {
  readonly call: ToolUseBlock
  /** Present only after the tool returned and its result was checkpointed. */
  readonly commit?: ToolCallCommitCheckpoint
  /** Present while this exact validated invocation awaits or consumes review. */
  readonly approvalRequest?: ApprovalRequest
  /** Decision loaded from the primary approval ledger during restore. */
  readonly approvalDecision?: ApprovalDecisionRecord
}

/**
 * Serializable runner state for one task that has started but is not yet
 * reflected in the queue's completed-task partition.
 */
export interface InFlightTaskCheckpoint {
  readonly taskId: string
  readonly assignee: string
  /** The next safe action when this state is restored. */
  readonly phase: 'awaiting_model' | 'executing_tools' | 'completed'
  /** Full model context, including the task's initial user message. */
  readonly conversationMessages: readonly LLMMessage[]
  /** Messages produced by the runner, excluding the initial user message. */
  readonly messages: readonly LLMMessage[]
  readonly tokenUsage: TokenUsage
  readonly toolCalls: readonly ToolCallRecord[]
  /** Number of completed model turns. */
  readonly turns: number
  /** Present while an assistant tool-use turn is being committed. */
  readonly pendingToolCalls?: readonly PendingToolCallCheckpoint[]
  /** Optional warning text appended beside the pending tool results. */
  readonly pendingToolResultText?: string
  /** Final assistant output when `phase` is `completed`. */
  readonly finalOutput?: string
  /** Whether loop detection has already injected its first warning. */
  readonly loopWarned?: boolean
  readonly loopDetected?: boolean
  readonly budgetExceeded?: boolean
}

interface CheckpointSnapshotBase {
  readonly mode: 'runTeam' | 'runTasks' | 'runFromPlan'
  readonly createdAt: string
  /** Validated per-run metadata inherited by future restore attempts. */
  readonly metadata?: Readonly<Record<string, TraceAttributeValue>>
  readonly goal?: string
  readonly queue: TaskQueueSnapshot
  readonly sharedMemory?: SharedMemorySnapshot
  readonly messageBus?: MessageBusSnapshot
  /**
   * Shared-memory turn counter at checkpoint time. Persisted separately from
   * {@link sharedMemory} so TTL/expiry stays correct on resume even when the
   * full entry snapshot is omitted (checkpoint store === shared-memory store).
   */
  readonly turnCount?: number
  readonly completedTaskResults: readonly CompletedTaskCheckpoint[]
}

/** Legacy checkpoint schema, retained for read compatibility. */
export interface CheckpointSnapshotV1 extends CheckpointSnapshotBase {
  readonly version: 1
  readonly runId?: string
}

/** Identity persisted by identity-aware checkpoint schemas (v2 and later). */
export interface CheckpointRunIdentity {
  readonly runId: string
  readonly attempt: number
  readonly lastTraceId: string
  readonly lastRootSpanId: string
}

/** Legacy identity-aware checkpoint schema, retained for read compatibility. */
export interface CheckpointSnapshotV2 extends CheckpointSnapshotBase {
  readonly version: 2
  readonly identity: CheckpointRunIdentity
}

/** Legacy checkpoint schema with mid-task runner recovery. */
export interface CheckpointSnapshotV3 extends CheckpointSnapshotBase {
  readonly version: 3
  readonly identity: CheckpointRunIdentity
  readonly inFlightTasks: readonly InFlightTaskCheckpoint[]
}

/** Checkpoint schema with durable approval continuation state. */
export interface CheckpointSnapshotV4 extends CheckpointSnapshotBase {
  readonly version: 4
  readonly identity: CheckpointRunIdentity
  readonly inFlightTasks: readonly InFlightTaskCheckpoint[]
  /** Requests whose reviewed boundary has not yet been consumed by execution. */
  readonly pendingApprovals: readonly ApprovalRequest[]
  /** Durable decisions already consumed or ready to be consumed by this run. */
  readonly approvalDecisions: readonly ApprovalDecisionRecord[]
}

/** Full persisted checkpoint for a task-based run. */
export type CheckpointSnapshot =
  | CheckpointSnapshotV1
  | CheckpointSnapshotV2
  | CheckpointSnapshotV3
  | CheckpointSnapshotV4

/** A single key-value record stored in a {@link MemoryStore}. */
export interface MemoryEntry {
  readonly key: string
  readonly value: string
  readonly metadata?: Readonly<Record<string, unknown>>
  readonly createdAt: Date
  /**
   * Optional turn-count expiry. When set, the entry is considered expired
   * once the {@link SharedMemory} turn counter reaches or exceeds this value.
   * Computed at write time as `currentTurn + ttlTurns`. Stores that don't
   * implement {@link MemoryStore.setWithExpiry} will not have this field set.
   */
  readonly expiresAtTurn?: number
}

/**
 * Persistent (or in-memory) key-value store shared across agents.
 * Implementations may be backed by Redis, SQLite, or plain objects.
 */
export interface MemoryStore {
  get(key: string): Promise<MemoryEntry | null>
  set(key: string, value: string, metadata?: Record<string, unknown>): Promise<void>
  /**
   * Optional atomic compare-and-set used by durable approval decisions.
   * `expectedValue: null` means the key must not exist. Implementations that
   * cannot make the comparison and write atomic across their supported writer
   * scope must omit this method; suspendable approvals fail closed without it.
   */
  compareAndSet?(
    key: string,
    expectedValue: string | null,
    value: string,
    metadata?: Record<string, unknown>,
  ): Promise<boolean>
  /**
   * Optional: write an entry with a turn-count expiry. Stores that don't
   * implement this method silently lose TTL semantics — callers (e.g.
   * {@link SharedMemory}) should fall back to {@link set} and not enforce
   * expiry on entries from those backends.
   */
  setWithExpiry?(
    key: string,
    value: string,
    expiresAtTurn: number,
    metadata?: Record<string, unknown>,
  ): Promise<void>
  list(): Promise<MemoryEntry[]>
  delete(key: string): Promise<void>
  clear(): Promise<void>
}

/** Options of one chat call. */
export interface LLMChatOptions {
  readonly model: string
  readonly tools?: readonly LLMToolDef[]
  readonly maxTokens?: number
  readonly temperature?: number
  readonly systemPrompt?: string
  readonly abortSignal?: AbortSignal
}

/**
 * Provider-agnostic interface that every LLM backend must implement.
 *
 * @example
 * ```ts
 * const adapter: LLMAdapter = createAdapter('anthropic')
 * const response = await adapter.chat(messages, { model: 'claude-opus-4-6' })
 * ```
 */
export interface LLMAdapter {
  /** Human-readable provider name, e.g. `'anthropic'` or `'openai'`. */
  readonly name: string

  /**
   * Send a chat request and return the complete response.
   * Throws on non-retryable API errors.
   */
  chat(messages: LLMMessage[], options: LLMChatOptions): Promise<LLMResponse>

}
